[project]
name = "aah_code"
version = "0.0.1"
description = "AAH v0: matched case energy"
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "pydantic",
    "wandb",
    "fire",
    "tqdm",
    "pytest",
    "ipykernel",
    "plotly",
    "numpy",
    "physics-tenpy",
    "python-dotenv",
    "tabulate",
    "quspin",
    "pandas",
    "scipy",
]

[project.optional-dependencies]
cuda = [
    "cupy-cuda12x"
]

[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "aah_code*",
]

[tool.cluster.remote]
user = "dmitry2"
host = "cc-login.campuscluster.illinois.edu"
project_root = "/projects/illinois/eng/physics/bbradlyn/dmitry2/k_blocking/new_code"

[tool.cluster.rsync]
excludes = [
    ".venv/",
]
delete = true

[tool.cluster.sbatch]
script = "aah/aah_code/cluster_model/scripts/slurm/run_convergence.sbatch"
extra_args = ""

[tool.cluster.environment]
modules = [
    "anaconda3/2024.10",
    "cuda/12.6",
]
activate = "source activate torch_env"

[tool.cluster.environment.variables]

[tool.cluster.run]
working_dir = "."
command = "python -m aah_code.cluster_model.main"
args = []
